Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -9,34 +9,37 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - name: Something that might fail
-        run: exit 0
+        run: exit 1
+      - name: Set issue title
+        run: |
+            echo "title=[Failed-AutoCherryPick] - ${{ github.event.pull_request.title }}" >> "$GITHUB_ENV"
       - name: Create Issue on Failed workflow
         if: ${{ failure() }}
         uses: dacbd/create-issue-action@main
         with:
           token: ${{ github.token }}
           title: |
-            [Failed-AutoCherryPick] - ${{ github.event.pull_request.title }}
+            ${{ env.title }}
           body: |
             #### Auto-Cherry-Pick WorkFlow Failure:
-            
+
             - [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
-            
+
             - [PR Number](https://github.com/${{ github.repository }}/pull/${{ github.event.number }})
-            
+
             - Workflow Name - `${{ github.workflow }}`
-            
+
             - Job -           `${{ github.job }}`
-            
+
             - Status -        `${{ job.status }}`
-          labels: auto-cherry-pick-failed
+
+          labels: Failed_AutoCherryPick
           assignees: "${{ github.event.pull_request.user.login }}"
 
       - name: Google Chat Notification - Robottelo
         if: ${{ failure() }}
         uses: Co-qn/google-chat-notification@releases/v1
         with:
-          name: "[Failed-AutoCherryPick] - ${{ github.event.pull_request.title }}"
+          name: ${{ env.title }}
           url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
           status: failure
-
